# Generated by Django 4.2.24 on 2025-09-24 10:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Enter a valid email address.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('first_name', models.CharField(help_text="User's first name", max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(help_text="User's last name", max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, help_text='Optional. Contact phone number', max_length=20, null=True, verbose_name='phone number')),
                ('profile_image', models.ImageField(blank=True, help_text="Optional. User's profile picture", null=True, upload_to='profile_images/', verbose_name='profile image')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.', verbose_name='verified')),
                ('role', models.CharField(choices=[('owner', 'Business Owner'), ('manager', 'Business Manager'), ('staff', 'Staff Member'), ('viewer', 'Viewer')], default='owner', help_text="User's role in the system", max_length=20, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the account was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the account was last updated', verbose_name='updated at')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text="IP address of the user's last login", null=True, verbose_name='last login IP')),
                ('password_reset_token', models.CharField(blank=True, help_text='Token for password reset functionality', max_length=255, null=True, verbose_name='password reset token')),
                ('password_reset_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for password reset token', null=True, verbose_name='password reset expires at')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=255, null=True, verbose_name='email verification token')),
                ('email_verification_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for email verification token', null=True, verbose_name='email verification expires at')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts', verbose_name='failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account lock expiration time', null=True, verbose_name='account locked until')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled', verbose_name='two-factor authentication enabled')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Backup codes for two-factor authentication', verbose_name='backup codes')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text="User's application preferences and settings", verbose_name='user preferences')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the session was created', verbose_name='IP address')),
                ('user_agent', models.TextField(help_text='Browser user agent string', verbose_name='user agent')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', help_text='Type of device used for this session', max_length=50, verbose_name='device type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created', verbose_name='created at')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp for this session', verbose_name='last activity')),
                ('expires_at', models.DateTimeField(help_text='When the session expires', verbose_name='expires at')),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'auth_user_session',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='auth_session_user_active_idx'), models.Index(fields=['session_key'], name='auth_session_key_idx'), models.Index(fields=['expires_at'], name='auth_session_expires_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Unique token for password reset', max_length=255, unique=True, verbose_name='reset token')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the reset was requested', verbose_name='IP address')),
                ('user_agent', models.TextField(help_text='Browser user agent string', verbose_name='user agent')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this reset token has been used', verbose_name='is used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the reset was requested', verbose_name='created at')),
                ('expires_at', models.DateTimeField(help_text='When the reset token expires', verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the reset token was used', null=True, verbose_name='used at')),
                ('user', models.ForeignKey(help_text='User who requested the password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'db_table': 'auth_password_reset',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='auth_reset_token_idx'), models.Index(fields=['user', 'is_used'], name='auth_reset_user_used_idx'), models.Index(fields=['expires_at'], name='auth_reset_expires_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='auth_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='auth_user_created_idx'),
        ),
    ]
