# Generated by Django 4.2.24 on 2025-09-24 11:59

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authentication.models.CustomUserManager()),
            ],
        ),
    ]
