# Generated by Django 4.2.24 on 2025-09-24 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the business', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the restaurant or business', max_length=255, verbose_name='business name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the business', max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of the business', verbose_name='description')),
                ('business_type', models.CharField(choices=[('fast_food', 'Fast Food'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('bar', 'Bar'), ('food_truck', 'Food Truck'), ('other', 'Other')], default='fast_food', help_text='Type of food service business', max_length=20, verbose_name='business type')),
                ('email', models.EmailField(blank=True, help_text='Primary contact email for the business', max_length=254, verbose_name='business email')),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('website', models.URLField(blank=True, help_text='Business website URL', verbose_name='website')),
                ('address_line_1', models.CharField(blank=True, help_text='Street address', max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, verbose_name='city')),
                ('state_province', models.CharField(blank=True, help_text='State or province', max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, help_text='ZIP or postal code', max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='United States', help_text='Country name', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Business operating hours for each day of the week', verbose_name='business hours')),
                ('logo', models.ImageField(blank=True, help_text='Business logo image', null=True, upload_to='business_logos/', verbose_name='logo')),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for displays and marketing', null=True, upload_to='business_banners/', verbose_name='banner image')),
                ('primary_color', models.CharField(default='#1f2937', help_text='Primary brand color in hex format (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#374151', help_text='Secondary brand color in hex format (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='secondary color')),
                ('accent_color', models.CharField(default='#3b82f6', help_text='Accent brand color in hex format (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='accent color')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Business-specific settings and preferences', verbose_name='business settings')),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan')], default='free', help_text='Current subscription plan', max_length=20, verbose_name='subscription plan')),
                ('plan_expires_at', models.DateTimeField(blank=True, help_text='When the current plan expires', null=True, verbose_name='plan expires at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is currently active', verbose_name='is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the business has been verified', verbose_name='is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the business was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the business was last updated', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses_business',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', help_text="User's role in the business", max_length=20, verbose_name='role')),
                ('permissions', models.JSONField(default=list, help_text='Specific permissions granted to this member', verbose_name='permissions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active', verbose_name='is active')),
                ('invited_at', models.DateTimeField(blank=True, help_text='When the invitation was sent', null=True, verbose_name='invited at')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined the business', verbose_name='joined at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the membership was last updated', verbose_name='updated at')),
                ('invitation_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='accepted', help_text='Status of the business invitation', max_length=20, verbose_name='invitation status')),
                ('invitation_token', models.CharField(blank=True, help_text='Token for invitation acceptance', max_length=255, null=True, verbose_name='invitation token')),
                ('invitation_expires_at', models.DateTimeField(blank=True, help_text='When the invitation expires', null=True, verbose_name='invitation expires at')),
                ('business', models.ForeignKey(help_text='Business this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who is a member of the business', on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Member',
                'verbose_name_plural': 'Business Members',
                'db_table': 'businesses_member',
                'ordering': ['role', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the person being invited', max_length=254, verbose_name='invitee email')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', help_text='Role to be assigned to the invited user', max_length=20, verbose_name='role')),
                ('permissions', models.JSONField(default=list, help_text='Permissions to be granted to the invited user', verbose_name='permissions')),
                ('message', models.TextField(blank=True, help_text='Optional message to include with the invitation', verbose_name='invitation message')),
                ('token', models.CharField(help_text='Unique token for invitation acceptance', max_length=255, unique=True, verbose_name='invitation token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the invitation', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was sent', verbose_name='created at')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires', verbose_name='expires at')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the invitation was responded to', null=True, verbose_name='responded at')),
                ('accepted_by', models.ForeignKey(blank=True, help_text='User who accepted the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_business_invitations', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(help_text='Business sending the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='businesses.business')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_business_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Invitation',
                'verbose_name_plural': 'Business Invitations',
                'db_table': 'businesses_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='members',
            field=models.ManyToManyField(help_text='Staff members with access to this business', related_name='businesses', through='businesses.BusinessMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(help_text='Primary owner of the business', on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['business', 'role'], name='member_business_role_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['user'], name='member_user_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['is_active'], name='member_active_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['invitation_token'], name='member_token_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmember',
            unique_together={('business', 'user')},
        ),
        migrations.AddIndex(
            model_name='businessinvitation',
            index=models.Index(fields=['business', 'status'], name='invitation_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvitation',
            index=models.Index(fields=['email'], name='invitation_email_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvitation',
            index=models.Index(fields=['token'], name='invitation_token_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvitation',
            index=models.Index(fields=['expires_at'], name='invitation_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='business_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='business_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active'], name='business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type'], name='business_type_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_at'], name='business_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='business_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='business_longitude_range'),
        ),
    ]
