-- 2025-12-21: Auth refresh tokens, API keys, webhooks, idempotency keys, audit logs

-- Media file processing state
ALTER TABLE MediaFiles
  ADD COLUMN IF NOT EXISTS ProcessingStatus VARCHAR(20) NOT NULL DEFAULT 'uploaded',
  ADD COLUMN IF NOT EXISTS ProcessingError TEXT,
  ADD COLUMN IF NOT EXISTS ValidatedAt TIMESTAMP WITH TIME ZONE;

-- Display status fields
ALTER TABLE Displays
  ADD COLUMN IF NOT EXISTS LastHeartbeatAt TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS AppVersion VARCHAR(50),
  ADD COLUMN IF NOT EXISTS DeviceInfo JSONB,
  ADD COLUMN IF NOT EXISTS LastIp VARCHAR(64);

-- Refresh tokens
CREATE TABLE IF NOT EXISTS RefreshTokens (
  RefreshTokenID BIGSERIAL PRIMARY KEY,
  OrganizationID INT NOT NULL,
  UserID INT NOT NULL,
  TokenHash VARCHAR(128) NOT NULL UNIQUE,
  ExpiresAt TIMESTAMP WITH TIME ZONE NOT NULL,
  RevokedAt TIMESTAMP WITH TIME ZONE,
  LastUsedAt TIMESTAMP WITH TIME ZONE,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (OrganizationID) REFERENCES Organizations(OrganizationID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- API keys
CREATE TABLE IF NOT EXISTS ApiKeys (
  ApiKeyID BIGSERIAL PRIMARY KEY,
  OrganizationID INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  KeyHash VARCHAR(128) NOT NULL UNIQUE,
  Scopes TEXT NOT NULL,
  CreatedByUserID INT,
  ExpiresAt TIMESTAMP WITH TIME ZONE,
  RevokedAt TIMESTAMP WITH TIME ZONE,
  LastUsedAt TIMESTAMP WITH TIME ZONE,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (OrganizationID) REFERENCES Organizations(OrganizationID) ON DELETE CASCADE,
  FOREIGN KEY (CreatedByUserID) REFERENCES Users(UserID) ON DELETE SET NULL
);

-- Webhooks
CREATE TABLE IF NOT EXISTS Webhooks (
  WebhookID BIGSERIAL PRIMARY KEY,
  OrganizationID INT NOT NULL,
  Url VARCHAR(1024) NOT NULL,
  Secret VARCHAR(255),
  Events TEXT NOT NULL DEFAULT '*',
  IsActive BOOLEAN NOT NULL DEFAULT TRUE,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (OrganizationID) REFERENCES Organizations(OrganizationID) ON DELETE CASCADE
);

-- Idempotency keys
CREATE TABLE IF NOT EXISTS IdempotencyKeys (
  IdempotencyKey VARCHAR(128) PRIMARY KEY,
  OrganizationID INT,
  Method VARCHAR(16) NOT NULL,
  Path VARCHAR(255) NOT NULL,
  ResponseStatus INT NOT NULL,
  ResponseBody TEXT NOT NULL,
  ExpiresAt TIMESTAMP WITH TIME ZONE NOT NULL,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Audit logs
CREATE TABLE IF NOT EXISTS AuditLogs (
  AuditLogID BIGSERIAL PRIMARY KEY,
  OrganizationID INT NOT NULL,
  UserID INT,
  Action VARCHAR(128) NOT NULL,
  ObjectType VARCHAR(64),
  ObjectId VARCHAR(64),
  Details JSONB,
  RequestId VARCHAR(64),
  IpAddress VARCHAR(64),
  UserAgent VARCHAR(255),
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (OrganizationID) REFERENCES Organizations(OrganizationID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL
);
