# Generated by Django 4.2.24 on 2025-09-24 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the display', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the display', max_length=100, verbose_name='display name')),
                ('location', models.CharField(blank=True, help_text="Physical location of the display (e.g., 'Main Counter', 'Drive-thru')", max_length=255, verbose_name='location')),
                ('device_type', models.CharField(choices=[('android_tv', 'Android TV'), ('tablet', 'Tablet'), ('desktop', 'Desktop Computer'), ('smart_tv', 'Smart TV'), ('raspberry_pi', 'Raspberry Pi'), ('other', 'Other')], default='android_tv', help_text='Type of device used for this display', max_length=20, verbose_name='device type')),
                ('device_model', models.CharField(blank=True, help_text='Model/brand of the display device', max_length=100, verbose_name='device model')),
                ('screen_width', models.PositiveIntegerField(blank=True, help_text='Screen width in pixels', null=True, verbose_name='screen width (pixels)')),
                ('screen_height', models.PositiveIntegerField(blank=True, help_text='Screen height in pixels', null=True, verbose_name='screen height (pixels)')),
                ('screen_size_inches', models.DecimalField(blank=True, decimal_places=1, help_text='Screen diagonal size in inches', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='screen size (inches)')),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('auto', 'Auto-rotate')], default='landscape', help_text='Display orientation', max_length=20, verbose_name='orientation')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Display-specific settings and preferences', verbose_name='display settings')),
                ('pairing_code', models.CharField(blank=True, help_text='8-character code for pairing new displays', max_length=8, unique=True, verbose_name='pairing code')),
                ('pairing_expires_at', models.DateTimeField(blank=True, help_text='When the current pairing code expires', null=True, verbose_name='pairing expires at')),
                ('device_token', models.CharField(blank=True, help_text='Unique token for device authentication', max_length=255, verbose_name='device token')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('connecting', 'Connecting'), ('error', 'Error'), ('updating', 'Updating')], default='offline', help_text='Current status of the display', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this display is currently active', verbose_name='is active')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Current IP address of the display device', null=True, verbose_name='IP address')),
                ('mac_address', models.CharField(blank=True, help_text='MAC address of the display device', max_length=17, validators=[django.core.validators.RegexValidator('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='MAC address')),
                ('app_version', models.CharField(blank=True, help_text='Version of the display app', max_length=20, verbose_name='app version')),
                ('os_version', models.CharField(blank=True, help_text='Operating system version', max_length=50, verbose_name='OS version')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the display was seen online', null=True, verbose_name='last seen at')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Last heartbeat received from the display', null=True, verbose_name='last heartbeat at')),
                ('connection_count', models.PositiveIntegerField(default=0, help_text='Total number of times display has connected', verbose_name='connection count')),
                ('last_error', models.TextField(blank=True, help_text='Last error message from the display', verbose_name='last error')),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When the last error occurred', null=True, verbose_name='last error at')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, help_text='Performance and diagnostic metrics', verbose_name='performance metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the display was first registered', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the display was last updated', verbose_name='updated at')),
                ('paired_at', models.DateTimeField(blank=True, help_text='When the display was paired with the business', null=True, verbose_name='paired at')),
                ('business', models.ForeignKey(help_text='Business this display belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='businesses.business')),
                ('current_menu', models.ForeignKey(blank=True, help_text='Currently assigned menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_displays', to='menus.menu')),
                ('paired_by', models.ForeignKey(blank=True, help_text='User who paired this display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_displays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Display',
                'verbose_name_plural': 'Displays',
                'db_table': 'displays_display',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisplaySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique identifier for this session', max_length=255, verbose_name='session ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the session started', verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session ended', null=True, verbose_name='ended at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active', verbose_name='is active')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the display during this session', verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the display', verbose_name='user agent')),
                ('total_uptime_seconds', models.PositiveIntegerField(default=0, help_text='Total uptime for this session in seconds', verbose_name='total uptime (seconds)')),
                ('heartbeat_count', models.PositiveIntegerField(default=0, help_text='Number of heartbeats received during this session', verbose_name='heartbeat count')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Number of errors during this session', verbose_name='error count')),
                ('menus_displayed', models.JSONField(default=list, help_text='List of menus displayed during this session', verbose_name='menus displayed')),
                ('performance_data', models.JSONField(blank=True, default=dict, help_text='Performance metrics collected during this session', verbose_name='performance data')),
                ('display', models.ForeignKey(help_text='Display associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='displays.display')),
            ],
            options={
                'verbose_name': 'Display Session',
                'verbose_name_plural': 'Display Sessions',
                'db_table': 'displays_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['display', 'is_active'], name='session_display_active_idx'), models.Index(fields=['started_at'], name='session_started_idx'), models.Index(fields=['session_id'], name='session_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisplayMenuAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was made', verbose_name='assigned at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current active assignment', verbose_name='is active')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_menu_assignments', to=settings.AUTH_USER_MODEL)),
                ('display', models.ForeignKey(help_text='Display that received the menu assignment', on_delete=django.db.models.deletion.CASCADE, related_name='menu_assignments', to='displays.display')),
                ('menu', models.ForeignKey(help_text='Menu that was assigned', on_delete=django.db.models.deletion.CASCADE, related_name='display_assignments', to='menus.menu')),
            ],
            options={
                'verbose_name': 'Display Menu Assignment',
                'verbose_name_plural': 'Display Menu Assignments',
                'db_table': 'displays_menu_assignment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['display', 'is_active'], name='assignment_display_active_idx'), models.Index(fields=['menu'], name='assignment_menu_idx'), models.Index(fields=['assigned_at'], name='assignment_assigned_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisplayGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the display group', max_length=100, verbose_name='group name')),
                ('description', models.TextField(blank=True, help_text='Description of the display group', verbose_name='description')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Settings applied to all displays in the group', verbose_name='group settings')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the group was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the group was last updated', verbose_name='updated at')),
                ('business', models.ForeignKey(help_text='Business this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='display_groups', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_display_groups', to=settings.AUTH_USER_MODEL)),
                ('default_menu', models.ForeignKey(blank=True, help_text='Default menu for displays in this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_display_groups', to='menus.menu')),
                ('displays', models.ManyToManyField(help_text='Displays in this group', related_name='groups', to='displays.display')),
            ],
            options={
                'verbose_name': 'Display Group',
                'verbose_name_plural': 'Display Groups',
                'db_table': 'displays_group',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='group_business_active_idx'), models.Index(fields=['created_at'], name='group_created_idx')],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['business', 'is_active'], name='display_business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['status'], name='display_status_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['pairing_code'], name='display_pairing_code_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['device_token'], name='display_device_token_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['last_seen_at'], name='display_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['ip_address'], name='display_ip_idx'),
        ),
        migrations.AddConstraint(
            model_name='display',
            constraint=models.CheckConstraint(check=models.Q(('screen_width__isnull', True), ('screen_width__gt', 0), _connector='OR'), name='display_positive_width'),
        ),
        migrations.AddConstraint(
            model_name='display',
            constraint=models.CheckConstraint(check=models.Q(('screen_height__isnull', True), ('screen_height__gt', 0), _connector='OR'), name='display_positive_height'),
        ),
    ]
