# Generated by Django 4.2.24 on 2025-09-24 10:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the menu', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the menu (e.g., 'Breakfast Menu', 'Lunch Specials')", max_length=100, verbose_name='menu name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the menu', max_length=100, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of the menu', verbose_name='description')),
                ('menu_type', models.CharField(choices=[('main', 'Main Menu'), ('breakfast', 'Breakfast Menu'), ('lunch', 'Lunch Menu'), ('dinner', 'Dinner Menu'), ('drinks', 'Drinks Menu'), ('desserts', 'Desserts Menu'), ('specials', 'Daily Specials'), ('seasonal', 'Seasonal Menu'), ('catering', 'Catering Menu'), ('kids', 'Kids Menu')], default='main', help_text='Type of menu', max_length=20, verbose_name='menu type')),
                ('version', models.CharField(default='1.0.0', help_text='Menu version for tracking changes', max_length=20, verbose_name='version')),
                ('version_notes', models.TextField(blank=True, help_text='Notes about changes in this version', verbose_name='version notes')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the menu display', null=True, upload_to='menu_backgrounds/', verbose_name='background image')),
                ('theme_color', models.CharField(blank=True, help_text='Primary theme color in hex format (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='theme color')),
                ('layout', models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout'), ('card', 'Card Layout'), ('magazine', 'Magazine Layout')], default='grid', help_text='Display layout for the menu', max_length=20, verbose_name='layout')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu is currently active', verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default menu for the business', verbose_name='is default')),
                ('available_from', models.TimeField(blank=True, help_text='Time when menu becomes available each day', null=True, verbose_name='available from')),
                ('available_until', models.TimeField(blank=True, help_text='Time when menu becomes unavailable each day', null=True, verbose_name='available until')),
                ('available_days', models.JSONField(default=list, help_text='Days of the week when menu is available (0=Monday)', verbose_name='available days')),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Cached count of total menu items', verbose_name='total items')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the menu was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the menu was last updated', verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the menu was published to displays', null=True, verbose_name='published at')),
                ('business', models.ForeignKey(help_text='Business this menu belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='businesses.business')),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menus_menu',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the category', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the menu category', max_length=100, verbose_name='category name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the category', max_length=100, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='Image to represent this category', null=True, upload_to='menu_categories/', verbose_name='category image')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g., for icon fonts)', max_length=50, verbose_name='icon')),
                ('color', models.CharField(blank=True, help_text='Category color in hex format (#RRGGBB)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='color')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear (lower numbers first)', verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently visible', verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to highlight this category prominently', verbose_name='is featured')),
                ('available_from', models.TimeField(blank=True, help_text='Time when category becomes available each day', null=True, verbose_name='available from')),
                ('available_until', models.TimeField(blank=True, help_text='Time when category becomes unavailable each day', null=True, verbose_name='available until')),
                ('available_days', models.JSONField(default=list, help_text='Days of the week when category is available (0=Monday)', verbose_name='available days')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the category was last updated', verbose_name='updated at')),
                ('business', models.ForeignKey(help_text='Business this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='businesses.business')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for nested categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menus.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'db_table': 'menus_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the menu item', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the menu item', max_length=100, verbose_name='item name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the item', max_length=100, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Description of the menu item', verbose_name='description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for compact displays', max_length=255, verbose_name='short description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the menu item', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price (for showing discounts)', max_digits=8, null=True, verbose_name='compare at price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for profit margin calculations', max_digits=8, null=True, verbose_name='cost price')),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('combo', 'Combo/Meal'), ('side', 'Side Item'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], default='food', help_text='Type of menu item', max_length=20, verbose_name='item type')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Caloric content', null=True, verbose_name='calories')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, help_text='Time required to prepare this item', null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='preparation time (minutes)')),
                ('dietary_info', models.JSONField(blank=True, default=dict, help_text='Dietary restrictions and allergen information', verbose_name='dietary information')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for filtering and search (e.g., 'spicy', 'vegetarian')", verbose_name='tags')),
                ('image', models.ImageField(blank=True, help_text='Main image of the menu item', null=True, upload_to='menu_items/', verbose_name='item image')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Additional images for this item', verbose_name='gallery images')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently available', verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to highlight this item prominently', verbose_name='is featured')),
                ('is_popular', models.BooleanField(default=False, help_text='Whether this is a popular/bestselling item', verbose_name='is popular')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which items appear (lower numbers first)', verbose_name='sort order')),
                ('track_inventory', models.BooleanField(default=False, help_text='Whether to track inventory for this item', verbose_name='track inventory')),
                ('inventory_count', models.PositiveIntegerField(default=0, help_text='Current inventory count', verbose_name='inventory count')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when inventory falls below this level', verbose_name='low stock threshold')),
                ('available_from', models.TimeField(blank=True, help_text='Time when item becomes available each day', null=True, verbose_name='available from')),
                ('available_until', models.TimeField(blank=True, help_text='Time when item becomes unavailable each day', null=True, verbose_name='available until')),
                ('available_days', models.JSONField(default=list, help_text='Days of the week when item is available (0=Monday)', verbose_name='available days')),
                ('customization_options', models.JSONField(blank=True, default=dict, help_text='Available customizations (sizes, add-ons, etc.)', verbose_name='customization options')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the item was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the item was last updated', verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menus.menucategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menu_items', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_menu_items', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(help_text='Menu this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menus_item',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['menu', 'is_active'], name='item_menu_active_idx'), models.Index(fields=['category'], name='item_category_idx'), models.Index(fields=['is_featured'], name='item_featured_idx'), models.Index(fields=['is_popular'], name='item_popular_idx'), models.Index(fields=['sort_order'], name='item_sort_idx'), models.Index(fields=['price'], name='item_price_idx')],
                'unique_together': {('menu', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['business', 'is_active'], name='category_business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['parent'], name='category_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['sort_order'], name='category_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['is_featured'], name='category_featured_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('business', 'slug')},
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['business', 'is_active'], name='menu_business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_type'], name='menu_type_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['is_default'], name='menu_default_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['published_at'], name='menu_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('business',), name='one_default_menu_per_business'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('business', 'slug')},
        ),
    ]
