name: Build and publish server image

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Linux binary presence
        id: checkbin
        run: |
          if [ -f Server/Linux/DisplayDeck.WebBroker ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
            echo "::notice title=Missing Linux binary::Skipping image publish because Server/Linux/DisplayDeck.WebBroker is not in the repo. The GitHub runner cannot compile Delphi; either commit the prebuilt binary, upload it as a release asset and use a download-based Dockerfile, or publish from a self-hosted runner/local dev machine."
          fi

      - name: Set up Docker Buildx
        if: steps.checkbin.outputs.present == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.checkbin.outputs.present == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        if: steps.checkbin.outputs.present == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/displaydeck-server
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        if: steps.checkbin.outputs.present == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
